In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import distance

In [56]:
letters = {'C':[1,0,0,0,0,1,1], 'l': [1,1,0,1,1,0,0], 'i':[1,1,0,1,0,0,1], 'n':[1,1,0,1,1,1,0], 't':[1,1,1,0,1,0,0], 'o':[1,1,0,1,1,1,1], 'H':[1,0,0,1,0,0,0], 'a':[1,1,0,0,0,0,1], 'r':[1,1,1,0,0,1,0], 'y':[1,1,1,1,0,0,1], 'K':[1,0,0,1,0,1,1], 'e':[1,1,0,0,1,0,1], 's':[1,1,1,0,0,1,1], 'P':[1,0,1,0,0,0,0], 'd':[1,1,0,0,1,0,0], 'F':[1,0,0,0,1,1,0], 'L':[1,0,0,1,1,0,0], 'G':[1,0,0,0,1,1,1], 'm':[1,1,0,1,1,0,1], 'w':[1,1,1,0,1,1,1], 'k':[1,1,0,1,0,1,1], 'S':[1,0,1,0,0,1,1]}

In [65]:
key_list = list(letters.keys())
value_list = list(letters.values())
position = value_list.index([1,1,0,1,0,0,1])
print(key_list[position])

i


In [4]:
letters['C']

[1, 0, 0, 0, 0, 1, 1]

In [5]:
Clinton = np.array([ [1,0,0,0,0,1,1],
                    [1,1,0,1,1,0,0],
                    [1,1,0,1,0,0,1],
                    [1,1,0,1,1,1,0],
                    [1,1,1,0,1,0,0],
                    [1,1,0,1,1,1,1],
                    [1,1,0,1,1,1,0] ])
Hillary = np.array([ [1,0,0,1,0,0,0],
                    [1,1,0,1,0,0,1],
                    [1,1,0,1,1,0,0],
                    [1,1,0,1,1,0,0],
                    [1,1,0,0,0,0,1],
                    [1,1,1,0,0,1,0],
                    [1,1,1,1,0,0,1] ])

Kenstar = np.array([ [1,0,0,1,0,1,1],
                    [1,1,0,0,1,0,1],
                    [1,1,0,1,1,1,0],
                    [1,1,1,0,0,1,1],
                    [1,1,1,0,1,0,0],
                    [1,1,0,0,0,0,1],
                    [1,1,1,0,0,1,0] ])



In [6]:
President = np.array([ [1,0,1,0,0,0,0],
                    [1,1,1,0,0,1,0],
                    [1,1,0,0,1,0,1],
                    [1,1,1,0,0,1,1],
                    [1,1,0,1,0,0,1],
                    [1,1,0,0,1,0,0],
                    [1,1,0,0,1,0,1],
                    [1,1,0,1,1,1,0],
                    [1,1,1,0,1,0,0] ])

FirstLady = np.array([ [1,0,0,0,1,1,0],
                    [1,1,0,1,0,0,1],
                    [1,1,1,0,0,1,0],
                    [1,1,1,0,0,1,1],
                    [1,1,1,0,1,0,0],
                    [1,0,0,1,1,0,0],
                    [1,1,0,0,0,0,1],
                    [1,1,0,0,1,0,0],
                    [1,1,1,1,0,0,1] ])

Gentleman = np.array([ [1,0,0,0,1,1,1],
                    [1,1,0,0,1,0,1],
                    [1,1,0,1,1,1,0],
                    [1,1,1,0,1,0,0],
                    [1,1,0,1,1,0,0],
                    [1,1,0,0,1,0,1],
                    [1,1,0,1,1,0,1],
                    [1,1,0,0,0,0,1],
                    [1,1,0,1,1,1,0] ])

In [7]:
S = np.hstack((Clinton.reshape(-1,1), Hillary.reshape(-1,1), Kenstar.reshape(-1,1)))
T = np.hstack((President.reshape(-1,1), FirstLady.reshape(-1,1), Gentleman.reshape(-1,1)))

In [8]:
W = np.zeros((S.shape[0], T.shape[0]))

In [9]:
for i in range(3):
  W += ((2*S[:,i].reshape(-1,1))-1) @ ((2*T[:,i].reshape(-1,1).T)-1)

In [10]:
print(W)

[[ 3. -3. -1. ...  1. -1. -1.]
 [-3.  3.  1. ... -1.  1.  1.]
 [-3.  3.  1. ... -1.  1.  1.]
 ...
 [-1.  1.  3. ...  1. -1. -1.]
 [ 1. -1.  1. ...  3.  1. -3.]
 [-1.  1. -1. ... -3. -1.  3.]]


In [11]:
def activation_function(input, threshold):
  output = np.copy(input)
  output[output > threshold] = 1
  output[output < threshold] = 0
  return output

In [12]:
def Xout(t, W):
    T1 = np.copy(t.reshape(-1, 1))
    return activation_function(T1.T @ W.T, 0).astype('int').reshape(7, 7)
def Yout(s, W):
    S = np.copy(s.reshape(-1, 1))
    return activation_function(S.T @ W, 0).astype('int').reshape(9,7)

In [13]:
for j in range(3):
  name_1 = []
  for i in range(9):
    position_2 = value_list.index(np.ndarray.tolist(T[:,j].reshape(9,7)[i]))
    name_1 += key_list[position_2]
  name = []
  for i in range(7):
    position_1 = value_list.index(np.ndarray.tolist(Xout(T[:,j],W)[i]))
    name += key_list[position_1]
  print('the name of'  + ' ' + name_1[0]+name_1[1]+name_1[2]+name_1[3]+name_1[4]+name_1[5]+name_1[6]+name_1[7]+name_1[8] + ' ' + 'is' + ' ' + name[0]+name[1]+name[2]+name[3]+name[4]+name[5]+name[6])

the name of President is Clinton
the name of FirstLady is Hillary
the name of Gentleman is Kenstar


In [14]:
for j in range(3):
  name_2 = []
  for i in range(7):
    position_3 = value_list.index(np.ndarray.tolist(S[:,j].reshape(7,7)[i]))
    name_2 += key_list[position_3]
  name_3 = []
  for i in range(9):
    position_4 = value_list.index(np.ndarray.tolist(Yout(S[:,j],W)[i]))
    name_3 += key_list[position_4]
  print('the feature of'  + ' ' + name_2[0]+name_2[1]+name_2[2]+name_2[3]+name_2[4]+name_2[5]+name_2[6] + ' ' + 'is' + ' ' + name_3[0]+name_3[1]+name_3[2]+name_3[3]+name_3[4]+name_3[5]+name_3[6]+name_3[7]+name_3[8])

the feature of Clinton is President
the feature of Hillary is FirstLady
the feature of Kenstar is Gentleman


In [46]:
def addingnoise(input, percent):
    noisyOutput = input.copy().reshape(-1, 1)
    choosenIndices = np.random.choice(noisyOutput.size, int(percent * noisyOutput.size / 100), replace=False)
    for index in choosenIndices:
        if noisyOutput[index] == 1:
            noisyOutput[index] = -1
        else:
            noisyOutput[index] = 1

    return noisyOutput.reshape(input.shape[0], input.shape[1])
def similarity_percent(predA, A):
    return np.sum((predA == A).astype('int')) / A.size

In [45]:

similarityPercent(Clinton, addingNoise(Clinton,60))

0.40816326530612246

In [33]:

Xout(addingnoise(President,10), W)

array([[1, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 1],
       [1, 1, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 1, 0, 0],
       [1, 1, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 0]])

In [47]:
iteration = 0
pc10 = 0
ph10 = 0
pk10 = 0
pp10 = 0
pf10 = 0
pg10 = 0
while iteration < 100:
  noisypc10 = addingnoise(Clinton, 10)
  noisyph10 = addingnoise(Hillary, 10)
  noisypk10 = addingnoise(Kenstar, 10)
  noisypp10 = addingnoise(President, 10)
  noisypf10 = addingnoise(FirstLady, 10)
  noisypg10 = addingnoise(Gentleman, 10)
  
  predpc10 = Yout(noisypc10, W)
  predph10 = Yout(noisyph10, W)
  predpk10 = Yout(noisypk10, W)
  predpp10 = Xout(noisypp10, W)
  predpf10 = Xout(noisypf10, W)
  predpg10 = Xout(noisypg10, W)

  if similarity_percent(predpc10, President) == 1:
    pc10 += 1
  if similarity_percent(predph10, FirstLady) == 1:
    ph10 += 1
  if similarity_percent(predpk10, Gentleman) == 1:
    pk10 += 1
  if similarity_percent(predpp10, Clinton) == 1:
    pp10 += 1
  if similarity_percent(predpf10, Hillary) == 1:
    pf10 += 1
  if similarity_percent(predpg10, Kenstar) == 1:
    pg10 += 1
  iteration += 1
print('In %f percent of times when we have 10 percent noise, we can completely restore feature of Clinton'%int(pc10))
print('In %f percent of times when we have 10 percent noise, we can completely restore feature of Hillary'%int(ph10))
print('In %f percent of times when we have 10 percent noise, we can completely restore feature of Kenstar'%int(pk10))
print('In %f percent of times when we have 10 percent noise, we can completely restore name of President'%int(pp10))
print('In %f percent of times when we have 10 percent noise, we can completely restore name of FirstLady'%int(pf10))
print('In %f percent of times when we have 10 percent noise, we can completely restore name of Gentleman'%int(pg10))



In 94.000000 percent of times when we have 10 percent noise, we can completely restore feature of Clinton
In 60.000000 percent of times when we have 10 percent noise, we can completely restore feature of Hillary
In 74.000000 percent of times when we have 10 percent noise, we can completely restore feature of Kenstar
In 82.000000 percent of times when we have 10 percent noise, we can completely restore name of President
In 63.000000 percent of times when we have 10 percent noise, we can completely restore name of FirstLady
In 96.000000 percent of times when we have 10 percent noise, we can completely restore name of Gentleman


In [48]:
iteration2 = 0
pc20 = 0
ph20 = 0
pk20 = 0
pp20 = 0
pf20 = 0
pg20 = 0
while iteration2 < 100:
  noisypc20 = addingnoise(Clinton, 20)
  noisyph20 = addingnoise(Hillary, 20)
  noisypk20 = addingnoise(Kenstar, 20)
  noisypp20 = addingnoise(President, 20)
  noisypf20 = addingnoise(FirstLady, 20)
  noisypg20 = addingnoise(Gentleman, 20)
  
  predpc20 = Yout(noisypc20, W)
  predph20 = Yout(noisyph20, W)
  predpk20 = Yout(noisypk20, W)
  predpp20 = Xout(noisypp20, W)
  predpf20 = Xout(noisypf20, W)
  predpg20 = Xout(noisypg20, W)

  if similarity_percent(predpc20, President) == 1:
    pc20 += 1
  if similarity_percent(predph20, FirstLady) == 1:
    ph20 += 1
  if similarity_percent(predpk20, Gentleman) == 1:
    pk20 += 1
  if similarity_percent(predpp20, Clinton) == 1:
    pp20 += 1
  if similarity_percent(predpf20, Hillary) == 1:
    pf20 += 1
  if similarity_percent(predpg20, Kenstar) == 1:
    pg20 += 1
  iteration2 += 1
print('In %f percent of times when we have 20 percent noise, we can completely restore feature of Clinton'%int(pc20))
print('In %f percent of times when we have 20 percent noise, we can completely restore feature of Hillary'%int(ph20))
print('In %f percent of times when we have 20 percent noise, we can completely restore feature of Kenstar'%int(pk20))
print('In %f percent of times when we have 20 percent noise, we can completely restore name of President'%int(pp20))
print('In %f percent of times when we have 20 percent noise, we can completely restore name of FirstLady'%int(pf20))
print('In %f percent of times when we have 20 percent noise, we can completely restore name of Gentleman'%int(pg20))

In 81.000000 percent of times when we have 20 percent noise, we can completely restore feature of Clinton
In 35.000000 percent of times when we have 20 percent noise, we can completely restore feature of Hillary
In 53.000000 percent of times when we have 20 percent noise, we can completely restore feature of Kenstar
In 69.000000 percent of times when we have 20 percent noise, we can completely restore name of President
In 52.000000 percent of times when we have 20 percent noise, we can completely restore name of FirstLady
In 84.000000 percent of times when we have 20 percent noise, we can completely restore name of Gentleman


In [57]:
Lewisky = np.array([ [1,0,0,1,1,0,0],
                    [1,1,0,0,1,0,1],
                    [1,1,1,0,1,1,1],
                    [1,1,0,1,0,0,1],
                    [1,1,1,0,0,1,1],
                    [1,1,0,1,0,1,1],
                    [1,1,1,1,0,0,1] ])
SweetGirl = np.array([ [1,0,1,0,0,1,1],
                    [1,1,1,0,1,1,1],
                    [1,1,0,0,1,0,1],
                    [1,1,0,0,1,0,1],
                    [1,1,1,0,1,0,0],
                    [1,0,0,0,1,1,1],
                    [1,1,0,1,0,0,1],
                    [1,1,1,0,0,1,0],
                    [1,1,0,1,1,0,0] ])

In [59]:
S_prime = np.hstack((Clinton.reshape(-1,1), Hillary.reshape(-1,1), Kenstar.reshape(-1,1), Lewisky.reshape(-1,1)))
T_prime = np.hstack((President.reshape(-1,1), FirstLady.reshape(-1,1), Gentleman.reshape(-1,1), SweetGirl.reshape(-1,1)))

In [75]:
W_prime = np.zeros((S_prime.shape[0], T_prime.shape[0]))

In [76]:
for i in range(4):
  W_prime += ((2*S_prime[:,i].reshape(-1,1))-1) @ ((2*T_prime[:,i].reshape(-1,1).T)-1)

In [77]:
for j in range(4):
  name_5 = []
  for i in range(9):
    position_5 = value_list.index(np.ndarray.tolist(T_prime[:,j].reshape(9,7)[i]))
    name_5 += key_list[position_5]
  name_6 = []
  for i in range(7):
    position_6 = value_list.index(np.ndarray.tolist(Xout(T_prime[:,j],W_prime)[i]))
    name_6 += key_list[position_6]
  print('the name of'  + ' ' + name_5[0]+name_5[1]+name_5[2]+name_5[3]+name_5[4]+name_5[5]+name_5[6]+name_5[7]+name_5[8] + ' ' + 'is' + ' ' + name_6[0]+name_6[1]+name_6[2]+name_6[3]+name_6[4]+name_6[5]+name_6[6])

the name of President is Lemisky


ValueError: ignored

In [78]:
for j in range(4):
  print(Xout(T_prime[:,j],W_prime))

[[1 0 0 1 1 0 0]
 [1 1 0 0 1 0 1]
 [1 1 0 1 1 0 1]
 [1 1 0 1 0 0 1]
 [1 1 1 0 0 1 1]
 [1 1 0 1 0 1 1]
 [1 1 1 1 0 0 1]]
[[1 0 0 1 0 0 0]
 [1 1 0 0 1 0 1]
 [1 1 0 1 1 0 0]
 [1 1 0 1 0 0 1]
 [1 1 1 0 0 0 1]
 [1 1 0 0 0 1 1]
 [1 1 1 1 0 0 1]]
[[1 0 0 1 0 0 0]
 [1 1 0 0 1 0 1]
 [1 1 0 1 1 1 0]
 [1 1 0 1 0 0 1]
 [1 1 1 0 0 0 1]
 [1 1 0 0 0 1 1]
 [1 1 1 1 0 0 1]]
[[1 0 0 1 1 0 0]
 [1 1 0 0 1 0 1]
 [1 1 0 1 1 1 1]
 [1 1 0 1 0 0 1]
 [1 1 1 0 0 1 1]
 [1 1 0 1 0 1 1]
 [1 1 1 1 0 0 1]]
