In [77]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import distance


In [95]:
letters = { 'C':[1,0,0,0,0,1,1],
            'S':[1,0,1,0,0,1,1],
            'K':[1,0,0,1,0,1,1],
            'F':[1,0,0,0,1,1,0],
            'P':[1,0,1,0,0,0,0],
            'H':[1,0,0,1,0,0,0],
            'G':[1,0,0,0,1,1,1],
            'L':[1,0,0,1,1,0,0],
            'i':[1,1,0,1,0,0,1],
            'l':[1,1,0,1,1,0,0], 
            'o':[1,1,0,1,1,1,1],
            'n':[1,1,0,1,1,1,0],
            't':[1,1,1,0,1,0,0],
            'r':[1,1,1,0,0,1,0], 
            'a':[1,1,0,0,0,0,1],
            'y':[1,1,1,1,0,0,1], 
            'e':[1,1,0,0,1,0,1], 
            'd':[1,1,0,0,1,0,0],
            's':[1,1,1,0,0,1,1],
            'm':[1,1,0,1,1,0,1],
            'w':[1,1,1,0,1,1,1], 
            'k':[1,1,0,1,0,1,1], }

In [96]:
x=list(letters.values())
for i in range(len(letters)):
  for j in range(7):
    if x[i][j] == 0:
      x[i][j]=-1
j=0
for i in list(letters.keys()):
  letters[i]=x[j]
  j =j+1
print(letters)

{'C': [1, -1, -1, -1, -1, 1, 1], 'S': [1, -1, 1, -1, -1, 1, 1], 'K': [1, -1, -1, 1, -1, 1, 1], 'F': [1, -1, -1, -1, 1, 1, -1], 'P': [1, -1, 1, -1, -1, -1, -1], 'H': [1, -1, -1, 1, -1, -1, -1], 'G': [1, -1, -1, -1, 1, 1, 1], 'L': [1, -1, -1, 1, 1, -1, -1], 'i': [1, 1, -1, 1, -1, -1, 1], 'l': [1, 1, -1, 1, 1, -1, -1], 'o': [1, 1, -1, 1, 1, 1, 1], 'n': [1, 1, -1, 1, 1, 1, -1], 't': [1, 1, 1, -1, 1, -1, -1], 'r': [1, 1, 1, -1, -1, 1, -1], 'a': [1, 1, -1, -1, -1, -1, 1], 'y': [1, 1, 1, 1, -1, -1, 1], 'e': [1, 1, -1, -1, 1, -1, 1], 'd': [1, 1, -1, -1, 1, -1, -1], 's': [1, 1, 1, -1, -1, 1, 1], 'm': [1, 1, -1, 1, 1, -1, 1], 'w': [1, 1, 1, -1, 1, 1, 1], 'k': [1, 1, -1, 1, -1, 1, 1]}


In [64]:
print(letters)

{'C': [1, -1, -1, -1, -1, 1, 1], 'S': [1, -1, 1, -1, -1, 1, 1], 'K': [1, -1, -1, 1, -1, 1, 1], 'F': [1, -1, -1, -1, 1, 1, -1], 'P': [1, -1, 1, -1, -1, -1, -1], 'H': [1, -1, -1, 1, -1, -1, -1], 'G': [1, -1, -1, -1, 1, 1, 1], 'L': [1, -1, -1, 1, 1, -1, -1], 'i': [1, 1, -1, 1, -1, -1, 1], 'l': [1, 1, -1, 1, 1, -1, -1], 'o': [1, 1, -1, 1, 1, 1, 1], 'n': [1, 1, -1, 1, 1, 1, -1], 't': [1, 1, 1, -1, 1, -1, -1], 'r': [1, 1, 1, -1, -1, 1, -1], 'a': [1, 1, -1, -1, -1, -1, 1], 'y': [1, 1, 1, 1, -1, -1, 1], 'e': [1, 1, -1, -1, 1, -1, 1], 'd': [1, 1, -1, -1, 1, -1, -1], 's': [1, 1, 1, -1, -1, 1, 1], 'm': [1, 1, -1, 1, 1, -1, 1], 'w': [1, 1, 1, -1, 1, 1, 1], 'k': [1, 1, -1, 1, -1, 1, 1]}


In [97]:
Clinton = np.array([letters['C'],letters['l'],letters['i'],letters['n'],letters['t'],letters['o'],letters['n']])
Hillary = np.array([letters['H'],letters['i'],letters['l'],letters['l'],letters['a'],letters['r'],letters['y']])
Kenstar = np.array([letters['K'],letters['e'],letters['n'],letters['s'],letters['t'],letters['a'],letters['r']])
President = np.array([letters['P'],letters['r'],letters['e'],letters['s'],letters['i'],letters['d'],letters['e'],letters['n'],letters['t']])
FirstLady = np.array([letters['F'],letters['i'],letters['r'],letters['s'],letters['t'],letters['L'],letters['a'],letters['d'],letters['y']])
Gentleman = np.array([letters['G'],letters['e'],letters['n'],letters['t'],letters['l'],letters['e'],letters['m'],letters['a'],letters['n']])

In [99]:
S = np.hstack((Clinton.reshape(-1,1), Hillary.reshape(-1,1), Kenstar.reshape(-1,1)))
T = np.hstack((President.reshape(-1,1), FirstLady.reshape(-1,1), Gentleman.reshape(-1,1)))
S,T

(array([[ 1,  1,  1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1,  1,  1],
        [-1, -1, -1],
        [ 1, -1,  1],
        [ 1, -1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [-1, -1, -1],
        [ 1,  1, -1],
        [ 1, -1,  1],
        [-1, -1, -1],
        [-1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [-1, -1, -1],
        [ 1,  1,  1],
        [-1,  1,  1],
        [-1, -1,  1],
        [ 1, -1, -1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [-1, -1,  1],
        [ 1,  1, -1],
        [ 1,  1, -1],
        [ 1, -1,  1],
        [-1, -1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1, -1,  1],
        [-1, -1, -1],
        [ 1, -1,  1],
        [-1, -1, -1],
        [-1,  1, -1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [-1,  1, -1],
        [ 1, -1, -1],
        [ 1, -1, -1],
        [ 1,  1, -1],
        [ 1, -1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [-1,  1,  1],
        [ 

In [100]:
FirstLady 

array([[ 1, -1, -1, -1,  1,  1, -1],
       [ 1,  1, -1,  1, -1, -1,  1],
       [ 1,  1,  1, -1, -1,  1, -1],
       [ 1,  1,  1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1, -1, -1],
       [ 1, -1, -1,  1,  1, -1, -1],
       [ 1,  1, -1, -1, -1, -1,  1],
       [ 1,  1, -1, -1,  1, -1, -1],
       [ 1,  1,  1,  1, -1, -1,  1]])

In [142]:
W = np.zeros((S.shape[0], T.shape[0]))
for i in range(3):
    W += S[:, i].reshape(-1, 1) @ T[:, i].reshape(-1, 1).T
print(W)

[[ 3. -3. -1. ...  1. -1. -1.]
 [-3.  3.  1. ... -1.  1.  1.]
 [-3.  3.  1. ... -1.  1.  1.]
 ...
 [-1.  1.  3. ...  1. -1. -1.]
 [ 1. -1.  1. ...  3.  1. -3.]
 [-1.  1. -1. ... -3. -1.  3.]]


In [145]:
def func (input, threshold):
  output = np.copy(input)
  output[output > threshold] = 1
  output[output < threshold] = -1
  return output
def YtoX(t, W):
    T1 = np.copy(t.reshape(-1, 1))
    return func (T1.T @ W.T, 0).astype('int32').reshape(7, 7)
def XtoY(s, W):
    S = np.copy(s.reshape(-1, 1))
    return func (S.T @ W, 0).astype('int32').reshape(9,7)

In [143]:
for j in range(3):
  name_1 = []
  for i in range(9):
    Ti = list(T[:,j].reshape(9,7)[i])

    position_2 = list(letters.values()).index(Ti)
    name_1 += list(letters.keys())[position_2]
  name = []
  for i in range(7):
    Si = list(YtoX(T[:,j],W)[i])
    position_1 =  list(letters.values()).index(Si)
    name += list(letters.keys())[position_1]
  print('semat '  + ' ' + name_1[0]+name_1[1]+name_1[2]+name_1[3]+name_1[4]+name_1[5]+name_1[6]+name_1[7]+name_1[8] + ' ' + 'baraye' + ' ' + name[0]+name[1]+name[2]+name[3]+name[4]+name[5]+name[6] +'ast')

semat  President baraye Clintonast
semat  FirstLady baraye Hillaryast
semat  Gentleman baraye Kenstarast


In [144]:
for j in range(3):
  name_2 = []
  for i in range(7):
    Ti =list(S[:,j].reshape(7,7)[i])
    position_3 =  list(letters.values()).index(Ti)
    name_2 += list(letters.keys())[position_3]
  name_3 = []
  for i in range(9):
    Si = list(XtoY(S[:,j],W)[i])
    position_4 = list(letters.values()).index(Si)
    name_3 += list(letters.keys())[position_4]
  print(' ' + name_2[0]+name_2[1]+name_2[2]+name_2[3]+name_2[4]+name_2[5]+name_2[6] + ' ' + 'semat' + ' ' + name_3[0]+name_3[1]+name_3[2]+name_3[3]+name_3[4]+name_3[5]+name_3[6]+name_3[7]+name_3[8]+'ra darad')

 Clinton semat Presidentra darad
 Hillary semat FirstLadyra darad
 Kenstar semat Gentlemanra darad


In [111]:
def Noise_Net (input, percent):
    noisyOutput = input.copy().reshape(-1, 1)
    choosenIndices = np.random.choice(noisyOutput.size, int(percent * noisyOutput.size / 100), replace=False)
    for index in choosenIndices:
        if noisyOutput[index] == 1:
            noisyOutput[index] = -1
        else:
            noisyOutput[index] = 1

    return noisyOutput.reshape(input.shape[0], input.shape[1])
def test_NET (predA, A):
    return np.sum((predA == A).astype('int')) / A.size

In [112]:
iteration = 0
pc10 = 0
ph10 = 0
pk10 = 0
pp10 = 0
pf10 = 0
pg10 = 0
while iteration < 100:
  noisypc10 = Noise_Net(Clinton, 10)
  noisyph10 = Noise_Net(Hillary, 10)
  noisypk10 = Noise_Net(Kenstar, 10)
  noisypp10 = Noise_Net(President, 10)
  noisypf10 = Noise_Net(FirstLady, 10)
  noisypg10 = Noise_Net(Gentleman, 10)
  
  predpc10 = XtoY(noisypc10, W)
  predph10 = XtoY(noisyph10, W)
  predpk10 = XtoY(noisypk10, W)
  predpp10 = YtoX(noisypp10, W)
  predpf10 = YtoX(noisypf10, W)
  predpg10 = YtoX(noisypg10, W)

  if test_NET(predpc10, President) == 1:
    pc10 += 1
  if test_NET(predph10, FirstLady) == 1:
    ph10 += 1
  if test_NET(predpk10, Gentleman) == 1:
    pk10 += 1
  if test_NET(predpp10, Clinton) == 1:
    pp10 += 1
  if test_NET(predpf10, Hillary) == 1:
    pf10 += 1
  if test_NET(predpg10, Kenstar) == 1:
    pg10 += 1
  iteration += 1
print('dar %f darsad mavaghe baraye 10 darsad khata hefz semat Clinton shabake dorost kar karde'%int(pc10))
print('dar %f darsad mavaghe baraye 10 darsad khata hefz semat Hillary shabake dorost kar karde'%int(ph10))
print('dar %f darsad mavaghe baraye 10 darsad khata hefz semat Kenstar shabake dorost kar karde'%int(pk10))
print('dar %f darsad mavaghe baraye 10 darsad khata hefz name President shabake dorost kar karde'%int(pp10))
print('dar %f darsad mavaghe baraye 10 darsad khata hefz name FirstLady shabake dorost kar karde'%int(pf10))
print('dar %f darsad mavaghe baraye 10 darsad khata hefz name Gentleman shabake dorost kar karde'%int(pg10))


dar 100.000000 darsad mavaghe baraye 10 darsad khata hefz semat Clinton shabake dorost kar karde
dar 100.000000 darsad mavaghe baraye 10 darsad khata hefz semat Hillary shabake dorost kar karde
dar 100.000000 darsad mavaghe baraye 10 darsad khata hefz semat Kenstar shabake dorost kar karde
dar 100.000000 darsad mavaghe baraye 10 darsad khata hefz name President shabake dorost kar karde
dar 99.000000 darsad mavaghe baraye 10 darsad khata hefz name FirstLady shabake dorost kar karde
dar 100.000000 darsad mavaghe baraye 10 darsad khata hefz name Gentleman shabake dorost kar karde


In [135]:
iteration = 0
pc20 = 0
ph20 = 0
pk20 = 0
pp20 = 0
pf20 = 0
pg20 = 0
while iteration < 100:
  noisypc20 = Noise_Net(Clinton, 20)
  noisyph20 = Noise_Net(Hillary, 20)
  noisypk20 = Noise_Net(Kenstar, 20)
  noisypp20 = Noise_Net(President, 20)
  noisypf20 = Noise_Net(FirstLady, 20)
  noisypg20 = Noise_Net(Gentleman, 20)
  
  predpc20 = XtoY(noisypc20, W)
  predph20 = XtoY(noisyph20, W)
  predpk20 = XtoY(noisypk20, W)
  predpp20 = YtoX(noisypp20, W)
  predpf20 = YtoX(noisypf20, W)
  predpg20 = YtoX(noisypg20, W)

  if test_NET(predpc20, President) == 1:
    pc20 += 1
  if test_NET(predph20, FirstLady) == 1:
    ph20 += 1
  if test_NET(predpk20, Gentleman) == 1:
    pk20 += 1
  if test_NET(predpp20, Clinton) == 1:
    pp20 += 1
  if test_NET(predpf20, Hillary) == 1:
    pf20 += 1
  if test_NET(predpg20, Kenstar) == 1:
    pg20 += 1
  iteration += 1
print('dar %f darsad mavaghe baraye 20 darsad khata hefz semat Clinton shabake dorost kar karde'%int(pc20))
print('dar %f darsad mavaghe baraye 20 darsad khata hefz semat Hillary shabake dorost kar karde'%int(ph20))
print('dar %f darsad mavaghe baraye 20 darsad khata hefz semat Kenstar shabake dorost kar karde'%int(pk20))
print('dar %f darsad mavaghe baraye 20 darsad khata hefz name President shabake dorost kar karde'%int(pp20))
print('dar %f darsad mavaghe baraye 20 darsad khata hefz name FirstLady shabake dorost kar karde'%int(pf20))
print('dar %f darsad mavaghe baraye 20 darsad khata hefz name Gentleman shabake dorost kar karde'%int(pg20))

dar 80.000000 darsad mavaghe baraye 20 darsad khata hefz semat Clinton shabake dorost kar karde
dar 70.000000 darsad mavaghe baraye 20 darsad khata hefz semat Hillary shabake dorost kar karde
dar 55.000000 darsad mavaghe baraye 20 darsad khata hefz semat Kenstar shabake dorost kar karde
dar 69.000000 darsad mavaghe baraye 20 darsad khata hefz name President shabake dorost kar karde
dar 66.000000 darsad mavaghe baraye 20 darsad khata hefz name FirstLady shabake dorost kar karde
dar 49.000000 darsad mavaghe baraye 20 darsad khata hefz name Gentleman shabake dorost kar karde


In [114]:
Lewisky = np.array([letters['L'],letters['e'],letters['w'],letters['i'],letters['s'],letters['k'],letters['y']])
SweetGirl = np.array([letters['S'],letters['w'],letters['e'],letters['e'],letters['t'],letters['G'],letters['i'],letters['r'],letters['l']])

In [ ]:
S2 = np.hstack((Clinton.reshape(-1,1), Hillary.reshape(-1,1), Kenstar.reshape(-1,1), Lewisky.reshape(-1,1)))
T2= np.hstack((President.reshape(-1,1), FirstLady.reshape(-1,1), Gentleman.reshape(-1,1), SweetGirl.reshape(-1,1)))
S2,T2

In [126]:
W2 = np.zeros((S2.shape[0], T2.shape[0]))
for i in range(4):
    W2 += S2[:, i].reshape(-1, 1) @ T2[:, i].reshape(-1, 1).T
W2

array([[ 4., -4.,  0., ...,  2., -2., -2.],
       [-4.,  4.,  0., ..., -2.,  2.,  2.],
       [-4.,  4.,  0., ..., -2.,  2.,  2.],
       ...,
       [-2.,  2.,  2., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  2.,  2., -2.],
       [ 0.,  0.,  0., ..., -2., -2.,  2.]])

In [129]:
for j in range(4):
  name_1 = []
  for i in range(9):
    Ti = list(T2[:,j].reshape(9,7)[i])

    position_2 = list(letters.values()).index(Ti)
    name_1 += list(letters.keys())[position_2]
  name = []
  for i in range(7):
    Si = list(YtoX(T2[:,j],W2)[i])
    position_1 =  list(letters.values()).index(Si)
    name += list(letters.keys())[position_1]
  print('the name of'  + ' ' + name_1[0]+name_1[1]+name_1[2]+name_1[3]+name_1[4]+name_1[5]+name_1[6]+name_1[7]+name_1[8] + ' ' + 'is' + ' ' + name[0]+name[1]+name[2]+name[3]+name[4]+name[5]+name[6])

the name of President is Clinton
the name of FirstLady is Hillary
the name of Gentleman is Kenstar


ValueError: ignored

In [141]:
iteration = 0
pl10 = 0
ps10 = 0
pl20 = 0
ps20 = 0
while iteration < 100:
  noisypl10 = Noise_Net(Lewisky, 10)
  noisyps10 = Noise_Net(SweetGirl, 10)
  noisypl20 = Noise_Net(Lewisky, 20)
  noisyps20 = Noise_Net(SweetGirl, 10)

  
  predpl10 = XtoY(noisypl10, W2)
  predps10 = YtoX(noisyps10, W2)
  predpl20 = XtoY(noisypl20, W2)
  predps20 = YtoX(noisyps20, W2)

  if test_NET(predpl10, SweetGirl) == 1:
    pl10 += 1
  if test_NET(predps10,  Lewisky) == 1:
    ps10 += 1
  if test_NET(predpl20, SweetGirl) == 1:
    pl20 += 1
  if test_NET(predps20,  Lewisky) == 1:
    ps20 += 1

  iteration += 1
print('dar %f darsad mavaghe baraye 10 darsad khata hefz semat Lewisky shabake dorost kar karde'%int(pl10))
print('dar %f darsad mavaghe baraye 10 darsad khata hefz name SweetGirl shabake dorost kar karde'%int(ps10))
print('dar %f darsad mavaghe baraye 20 darsad khata hefz semat Lewisky shabake dorost kar karde'%int(pl20))
print('dar %f darsad mavaghe baraye 20 darsad khata hefz name President shabake dorost kar karde'%int(ps20))


dar 73.000000 darsad mavaghe baraye 10 darsad khata hefz semat Lewisky shabake dorost kar karde
dar 37.000000 darsad mavaghe baraye 10 darsad khata hefz name SweetGirl shabake dorost kar karde
dar 57.000000 darsad mavaghe baraye 20 darsad khata hefz semat Lewisky shabake dorost kar karde
dar 35.000000 darsad mavaghe baraye 20 darsad khata hefz name President shabake dorost kar karde
